# Generated by Django 6.0.3 on 2026-05-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='role',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('developer', 'Developer'), ('qa', 'QA')], max_length=15),
        ),
    ]
