# Generated by Django 6.0.3 on 2026-05-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='environment',
            field=models.CharField(choices=[('local', 'Local'), ('staging', 'Staging'), ('uat', 'UAT'), ('production', 'Production')], default='staging', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('qa', 'QA'), ('done', 'Done'), ('closed', 'Closed'), ('reopen', 'Reopen')], default='open', max_length=20),
        ),
    ]
