# Generated by Django 6.0.3 on 2026-05-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_environment_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('hold', 'Hold'), ('scope_review', 'Scope Review'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('qa', 'QA'), ('done', 'Done'), ('closed', 'Closed'), ('reopen', 'Reopen')], default='open', max_length=20),
        ),
    ]
