# Generated by Django 6.0.3 on 2026-05-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('bug', 'Bug'), ('task', 'Task'), ('enhancement', 'Enhancement')], default='task', max_length=20),
        ),
    ]
