# Generated by Django 5.2.14 on 2026-05-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_issue_id_alter_issue_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('dev_in_progress', 'Dev In Progress'), ('ready_for_qa', 'Ready for QA'), ('qa_in_progress', 'QA In Progress'), ('in_review', 'In Review'), ('hold', 'Hold'), ('scope_review', 'Scope Review'), ('rejected', 'Rejected'), ('done', 'Done'), ('closed', 'Closed'), ('reopen', 'Reopen')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='issueremarklog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
