# Generated by Django 5.2.14 on 2026-05-08 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_alter_issue_id_alter_issue_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='related_issue',
            field=models.ForeignKey(blank=True, help_text='Optional related or parent issue', limit_choices_to={'issue_type': 'task'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_issues', to='issues.issue'),
        ),
    ]
