# Generated by Django 5.2.14 on 2026-05-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_issue_related_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='drive_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
