# Generated by Django 5.2.14 on 2026-05-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags used to classify this issue', related_name='issues', to='issues.tag'),
        ),
    ]
