# Generated by Django 5.2.14 on 2026-05-22 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_issue_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='co_assignees',
            field=models.ManyToManyField(blank=True, help_text='Additional users assigned to this issue', related_name='co_assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
