# Generated by Django 5.2.14 on 2026-05-22 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_issue_co_assignees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='co_assignees',
            field=models.ManyToManyField(blank=True, help_text='Additional users assigned to this issue', limit_choices_to={'is_superuser': False}, related_name='co_assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
